"""
Application-wide constants and configuration values.

This module centralizes all hardcoded values used throughout the application.
"""

# API Configuration
API_TITLE = "AI Task Inference API"
API_DESCRIPTION = "Backend for AI-powered task management with Qwen 2.5"
API_VERSION = "1.0.0"

# Ollama Configuration
DEFAULT_OLLAMA_MODEL = "qwen2.5:7b-instruct"
DEFAULT_OLLAMA_URL = "http://localhost:11434"

# CORS Configuration
DEFAULT_CORS_ORIGINS = "http://localhost:5173"

# Server Configuration
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8000

# Entity Types
ENTITY_TYPE_PERSON = "PERSON"
ENTITY_TYPE_PROJECT = "PROJECT"
ENTITY_TYPE_TEAM = "TEAM"
ENTITY_TYPE_DATE = "DATE"

VALID_ENTITY_TYPES = {
    ENTITY_TYPE_PERSON,
    ENTITY_TYPE_PROJECT,
    ENTITY_TYPE_TEAM,
    ENTITY_TYPE_DATE
}

# Relationship Types
RELATIONSHIP_WORKS_ON = "WORKS_ON"
RELATIONSHIP_COMMUNICATES_WITH = "COMMUNICATES_WITH"
RELATIONSHIP_HAS_DEADLINE = "HAS_DEADLINE"
RELATIONSHIP_MENTIONED_WITH = "MENTIONED_WITH"

VALID_RELATIONSHIP_TYPES = {
    RELATIONSHIP_WORKS_ON,
    RELATIONSHIP_COMMUNICATES_WITH,
    RELATIONSHIP_HAS_DEADLINE,
    RELATIONSHIP_MENTIONED_WITH
}

# Task Operations
TASK_OP_CREATE = "CREATE"
TASK_OP_UPDATE = "UPDATE"
TASK_OP_COMMENT = "COMMENT"
TASK_OP_ENRICH = "ENRICH"

VALID_TASK_OPERATIONS = {
    TASK_OP_CREATE,
    TASK_OP_UPDATE,
    TASK_OP_COMMENT,
    TASK_OP_ENRICH
}

# Task Statuses
TASK_STATUS_TODO = "todo"
TASK_STATUS_DOING = "doing"
TASK_STATUS_DONE = "done"

VALID_TASK_STATUSES = {
    TASK_STATUS_TODO,
    TASK_STATUS_DOING,
    TASK_STATUS_DONE
}

# Source Types
SOURCE_TYPE_SLACK = "slack"
SOURCE_TYPE_TRANSCRIPT = "transcript"
SOURCE_TYPE_MANUAL = "manual"

VALID_SOURCE_TYPES = {
    SOURCE_TYPE_SLACK,
    SOURCE_TYPE_TRANSCRIPT,
    SOURCE_TYPE_MANUAL
}

# Extraction Strategies
EXTRACTION_STRATEGY_FAST = "fast"
EXTRACTION_STRATEGY_DETAILED = "detailed"

# Quality Thresholds
QUALITY_THRESHOLD_HIGH = 0.7
QUALITY_THRESHOLD_MEDIUM = 0.6
SIMILARITY_THRESHOLD_HIGH = 0.75
SIMILARITY_THRESHOLD_MEDIUM = 0.60

# Retry Configuration
DEFAULT_MAX_RETRIES = 2

# Context Limits
MAX_STORED_TEXT_LENGTH = 1000
MAX_RECENT_TASKS_FOR_MATCHING = 50
MAX_TASKS_IN_SUMMARY = 10

# Complexity Scoring Weights
COMPLEXITY_WEIGHT_LONG_TEXT = 0.3
COMPLEXITY_WEIGHT_HIGH_DENSITY = 0.2
COMPLEXITY_WEIGHT_TECHNICAL = 0.2
COMPLEXITY_WEIGHT_DIVERSE = 0.3

# Team Metadata Fields
TEAM_META_PILLAR = "pillar"
TEAM_META_TEAM_NAME = "team_name"
TEAM_META_ROLE = "role"
