"""
Default keyboard shortcuts configuration
"""
from typing import List, Dict, Any


DEFAULT_SHORTCUTS: List[Dict[str, Any]] = [
    # ============= Global Shortcuts =============
    {
        "id": "global_help",
        "category": "global",
        "action": "toggle_help",
        "key": "?",
        "modifiers": [],
        "enabled": True,
        "description": "Toggle keyboard shortcuts help dialog",
    },
    {
        "id": "global_search",
        "category": "global",
        "action": "open_search",
        "key": "/",
        "modifiers": [],
        "enabled": True,
        "description": "Open search/command palette",
    },
    {
        "id": "global_command_palette",
        "category": "global",
        "action": "command_palette",
        "key": "k",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Open command palette",
    },
    {
        "id": "global_escape",
        "category": "global",
        "action": "escape",
        "key": "Escape",
        "modifiers": [],
        "enabled": True,
        "description": "Close dialogs or cancel operations",
    },
    {
        "id": "global_settings",
        "category": "global",
        "action": "open_settings",
        "key": ",",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Open settings panel",
    },

    # ============= Board Navigation Shortcuts =============
    {
        "id": "board_quick_add_todo",
        "category": "board",
        "action": "quick_add_todo",
        "key": "1",
        "modifiers": [],
        "enabled": True,
        "description": "Quick add task to To-Do column",
    },
    {
        "id": "board_quick_add_doing",
        "category": "board",
        "action": "quick_add_doing",
        "key": "2",
        "modifiers": [],
        "enabled": True,
        "description": "Quick add task to In Progress column",
    },
    {
        "id": "board_quick_add_done",
        "category": "board",
        "action": "quick_add_done",
        "key": "3",
        "modifiers": [],
        "enabled": True,
        "description": "Quick add task to Done column",
    },
    {
        "id": "board_prev_column_h",
        "category": "board",
        "action": "prev_column",
        "key": "h",
        "modifiers": [],
        "enabled": True,
        "description": "Move focus to previous column (vim-style)",
    },
    {
        "id": "board_prev_column_arrow",
        "category": "board",
        "action": "prev_column",
        "key": "ArrowLeft",
        "modifiers": [],
        "enabled": True,
        "description": "Move focus to previous column",
    },
    {
        "id": "board_next_column_l",
        "category": "board",
        "action": "next_column",
        "key": "l",
        "modifiers": [],
        "enabled": True,
        "description": "Move focus to next column (vim-style)",
    },
    {
        "id": "board_next_column_arrow",
        "category": "board",
        "action": "next_column",
        "key": "ArrowRight",
        "modifiers": [],
        "enabled": True,
        "description": "Move focus to next column",
    },
    {
        "id": "board_next_column_tab",
        "category": "board",
        "action": "next_column",
        "key": "Tab",
        "modifiers": [],
        "enabled": True,
        "description": "Tab to next column",
    },
    {
        "id": "board_prev_column_shift_tab",
        "category": "board",
        "action": "prev_column",
        "key": "Tab",
        "modifiers": ["shift"],
        "enabled": True,
        "description": "Shift+Tab to previous column",
    },

    # ============= Task Selection & Navigation =============
    {
        "id": "task_next_j",
        "category": "task",
        "action": "next_task",
        "key": "j",
        "modifiers": [],
        "enabled": True,
        "description": "Select next task in column (vim-style)",
    },
    {
        "id": "task_next_arrow",
        "category": "task",
        "action": "next_task",
        "key": "ArrowDown",
        "modifiers": [],
        "enabled": True,
        "description": "Select next task in column",
    },
    {
        "id": "task_prev_k",
        "category": "task",
        "action": "prev_task",
        "key": "k",
        "modifiers": [],
        "enabled": True,
        "description": "Select previous task in column (vim-style)",
    },
    {
        "id": "task_prev_arrow",
        "category": "task",
        "action": "prev_task",
        "key": "ArrowUp",
        "modifiers": [],
        "enabled": True,
        "description": "Select previous task in column",
    },
    {
        "id": "task_first",
        "category": "task",
        "action": "first_task",
        "key": "g",
        "modifiers": [],
        "enabled": True,
        "description": "Jump to first task (press 'g' twice)",
    },
    {
        "id": "task_last",
        "category": "task",
        "action": "last_task",
        "key": "G",
        "modifiers": ["shift"],
        "enabled": True,
        "description": "Jump to last task in column",
    },
    {
        "id": "task_open",
        "category": "task",
        "action": "open_task",
        "key": "Enter",
        "modifiers": [],
        "enabled": True,
        "description": "Open selected task details",
    },
    {
        "id": "task_preview",
        "category": "task",
        "action": "preview_task",
        "key": " ",
        "modifiers": [],
        "enabled": True,
        "description": "Quick preview task (Space)",
    },

    # ============= Task Quick Actions =============
    {
        "id": "task_new",
        "category": "task",
        "action": "new_task",
        "key": "n",
        "modifiers": [],
        "enabled": True,
        "description": "Create new task in current column",
    },
    {
        "id": "task_edit",
        "category": "task",
        "action": "edit_task",
        "key": "e",
        "modifiers": [],
        "enabled": True,
        "description": "Edit selected task",
    },
    {
        "id": "task_delete",
        "category": "task",
        "action": "delete_task",
        "key": "d",
        "modifiers": [],
        "enabled": True,
        "description": "Delete selected task",
    },
    {
        "id": "task_complete",
        "category": "task",
        "action": "toggle_complete",
        "key": "c",
        "modifiers": [],
        "enabled": True,
        "description": "Toggle task completion",
    },
    {
        "id": "task_archive",
        "category": "task",
        "action": "archive_task",
        "key": "x",
        "modifiers": [],
        "enabled": True,
        "description": "Archive selected task",
    },
    {
        "id": "task_duplicate",
        "category": "task",
        "action": "duplicate_task",
        "key": "y",
        "modifiers": [],
        "enabled": True,
        "description": "Duplicate selected task",
    },
    {
        "id": "task_move",
        "category": "task",
        "action": "move_task",
        "key": "m",
        "modifiers": [],
        "enabled": True,
        "description": "Move task to different column",
    },
    {
        "id": "task_priority",
        "category": "task",
        "action": "cycle_priority",
        "key": "p",
        "modifiers": [],
        "enabled": True,
        "description": "Cycle task priority",
    },

    # ============= Task Detail Dialog Shortcuts =============
    {
        "id": "dialog_save_close",
        "category": "dialog",
        "action": "save_and_close",
        "key": "Enter",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Save changes and close dialog",
    },
    {
        "id": "dialog_save",
        "category": "dialog",
        "action": "save",
        "key": "s",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Save changes without closing",
    },
    {
        "id": "dialog_close",
        "category": "dialog",
        "action": "close",
        "key": "Escape",
        "modifiers": [],
        "enabled": True,
        "description": "Close dialog without saving",
    },
    {
        "id": "dialog_focus_title",
        "category": "dialog",
        "action": "focus_title",
        "key": "t",
        "modifiers": ["alt"],
        "enabled": True,
        "description": "Focus title field",
    },
    {
        "id": "dialog_focus_description",
        "category": "dialog",
        "action": "focus_description",
        "key": "d",
        "modifiers": ["alt"],
        "enabled": True,
        "description": "Focus description field",
    },
    {
        "id": "dialog_add_due_date",
        "category": "dialog",
        "action": "add_due_date",
        "key": "d",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Open due date picker",
    },
    {
        "id": "dialog_set_priority",
        "category": "dialog",
        "action": "set_priority",
        "key": "p",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Open priority selector",
    },
    {
        "id": "dialog_add_tag",
        "category": "dialog",
        "action": "add_tag",
        "key": "t",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Focus tag input",
    },
    {
        "id": "dialog_delete",
        "category": "dialog",
        "action": "delete_task",
        "key": "Delete",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Delete current task",
    },

    # ============= Message Menu Shortcuts =============
    {
        "id": "message_toggle",
        "category": "message",
        "action": "toggle_messages",
        "key": "m",
        "modifiers": ["shift"],
        "enabled": True,
        "description": "Toggle message menu",
    },
    {
        "id": "message_next",
        "category": "message",
        "action": "next_message",
        "key": "ArrowDown",
        "modifiers": [],
        "enabled": True,
        "description": "Navigate to next message",
    },
    {
        "id": "message_prev",
        "category": "message",
        "action": "prev_message",
        "key": "ArrowUp",
        "modifiers": [],
        "enabled": True,
        "description": "Navigate to previous message",
    },
    {
        "id": "message_select",
        "category": "message",
        "action": "select_message",
        "key": "Enter",
        "modifiers": [],
        "enabled": True,
        "description": "Select/apply message",
    },
    {
        "id": "message_delete",
        "category": "message",
        "action": "delete_message",
        "key": "Delete",
        "modifiers": [],
        "enabled": True,
        "description": "Delete selected message",
    },
    {
        "id": "message_close",
        "category": "message",
        "action": "close_messages",
        "key": "Escape",
        "modifiers": [],
        "enabled": True,
        "description": "Close message menu",
    },

    # ============= Bulk Operations =============
    {
        "id": "bulk_select_all",
        "category": "bulk",
        "action": "select_all",
        "key": "a",
        "modifiers": ["ctrl"],
        "enabled": True,
        "description": "Select all tasks in column",
    },
    {
        "id": "bulk_delete",
        "category": "bulk",
        "action": "bulk_delete",
        "key": "d",
        "modifiers": ["shift"],
        "enabled": True,
        "description": "Delete all selected tasks",
    },
    {
        "id": "bulk_move",
        "category": "bulk",
        "action": "bulk_move",
        "key": "m",
        "modifiers": ["shift"],
        "enabled": True,
        "description": "Move all selected tasks",
    },
]


def get_default_shortcuts() -> List[Dict[str, Any]]:
    """Get default shortcuts configuration"""
    return DEFAULT_SHORTCUTS.copy()


def get_shortcuts_by_category(category: str) -> List[Dict[str, Any]]:
    """Get shortcuts filtered by category"""
    return [s for s in DEFAULT_SHORTCUTS if s["category"] == category]
